CXXFLAGS= -std=c++11

run:
	g++ main.cpp Conta.cpp Titular.cpp Cpf.cpp Funcionario.cpp Pessoa.cpp ContaPoupanca.cpp ContaCorrente.cpp Caixa.cpp Gerente.cpp Autenticavel.cpp -o forca.out
all:
	./forca.out